name: online_test_app
description: A test app created online by Conquest AI to verify internet integration
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter: sdk: '>=3.0.0 <4.0.0'
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  http: ^0.13.0
  sqflite: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
